{"name": "test_mul[错误]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -20 == 20", "trace": "self = <test_calNew.Testcal object at 0x000001DB2D7C7668>\nget_cal = <HogwartsLagou05.HomeWorkYing.PytestSecond.calculator.Calculator object at 0x000001DB2D76F400>, get_mul_datas = [10, -2, 20]\n\n>   ???\nE   assert -20 == 20\n\nC:\\Users\\zhy\\LGHomeworkUpload\\PytestSecond\\test_calNew.py:31: AssertionError"}, "attachments": [{"name": "stdout", "source": "5f07bfe3-3943-4a34-b751-243892a0afda-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_mul_datas", "value": "[10, -2, 20]"}], "start": 1627298403245, "stop": 1627298403245, "uuid": "76a173df-7438-453b-9892-0230fb05bab7", "historyId": "c78c05f3cbb0c23793413d5398540883", "testCaseId": "54ae541a9a5e2ef8bc1ca5d4061304c9", "fullName": "test_calNew.Testcal#test_mul", "labels": [{"name": "suite", "value": "test_calNew"}, {"name": "subSuite", "value": "Testcal"}, {"name": "host", "value": "DESKTOP-RLF34HD"}, {"name": "thread", "value": "24512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calNew"}]}